Added support for fast-m1
molecule-one/m1wrapper-python pull request #11
Opened 2022-09-27 13:25 UTC by kaletap

2022-09-27 16:01 UTC, ardcore requested changes
Suggestion: instead of a boolean `use_fast_m1` parameter, we could:
1. create an enum called `SearchEngine`, with variants `FAST_M1` and `CLASSIC` (there may be a better name :P)
2. have a parameter called `search_engine` accepting this enum, defaulting to `SearchEngine.CLASSIC`

This way we can easily add more "engines" in the future without introducing breaking changes in the API. It's also more coherent with other parameters, such as `detail_level` or `priority`.

@kaletap What do you think about this?

2022-09-28 11:43 UTC, kaletap commented
That's a very good point, thanks. I fixed it now. I used standard class instead of enum, because I think that it would be better if user could pass string directly rather than import `SearchEngine` and provide `SearchEngine.CLASSIC` or `SearchEngine.FAST_M1`. What do you think?

2022-09-28 22:01 UTC, ardcore requested changes
Thanks @kaletap!
I agree. In python 3.11, we'll be able to use StrEnum, but python 3.11 is not released as stable yet.

2022-09-29 07:41 UTC, kaletap commented on m1wrapper/search.py
> +        search_engine=False
No, fixed it now, thanks.

2022-09-29 18:53 UTC, ardcore commented
Thanks @kaletap. The code looks good. @brunokam can you please test this manually and merge if everything works? Thanks!

2022-09-29 18:55 UTC, ardcore approved these changes

2023-01-10 12:26 UTC, ardcore approved these changes
LGTM :)

2023-02-11 09:19 UTC, closed without merging